# Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

# Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

# Android
android.nonTransitiveRClass=true
android.useAndroidX=true
android.uniquePackageNames=false
android.dependency.useConstraints=false

# Maven Central Publishing (vanniktech/gradle-maven-publish-plugin)
GROUP=com.linroid.ketch
VERSION_NAME=0.0.2-dev1
SONATYPE_HOST=CENTRAL_PORTAL
SONATYPE_AUTOMATIC_RELEASE=true
#RELEASE_SIGNING_ENABLED=true
POM_DESCRIPTION=Ketch - Kotlin Multiplatform download manager library
POM_URL=https://github.com/linroid/Ketch
POM_INCEPTION_YEAR=2025
POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_DEVELOPER_ID=linroid
POM_DEVELOPER_NAME=linroid
POM_DEVELOPER_URL=https://github.com/linroid
POM_SCM_URL=https://github.com/linroid/Ketch
POM_SCM_CONNECTION=scm:git:git://github.com/linroid/Ketch.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/linroid/Ketch.git
